---
title: "mortality"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{mortality}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```{r}

```

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(monstR)
library(tidyverse)
```

We can use `ons_available_datasets()` to find out what datasets are available. There are several datasets on deaths and we want to download all of them. 

```{r}
datasets <- ons_available_datasets()

mortality_ids <- datasets %>% 
  filter(str_detect(id,'deaths')) %>% 
  pull(id)

mortality_ids
```
Get the available editions
```{r}
ids_and_editions <- map(mortality_ids, ons_available_editions ) %>% 
  set_names(mortality_ids) %>% 
  bind_rows(.id='id')
```


Set up the pipeline

```{r}
set_up_df <- monstr_pipeline_defaults() %>% 
  ons_datasets_setup()
```


Download all the data
```{r}
pmap_safely <- quietly(pmap)
pmap(ids_and_editions, ~ons_dataset_by_id(set_up_df, id=.x, edition = .y) %>% 
  ons_download(format="csv") %>% 
    	monstr_read_file() %>%  
	monstr_clean() %>%
	monstr_write_clean(format="all"))

```

There are some functions that clean the data and save it in a clean folder. 
**doesn't work**
```{r}

```

